/* This file was generated by syncqt. */
#ifndef QT_QTDESIGNER_VERSION_H
#define QT_QTDESIGNER_VERSION_H

#define QTDESIGNER_VERSION_STR "5.9.5"

#define QTDESIGNER_VERSION 0x050905

#endif // QT_QTDESIGNER_VERSION_H
